# Generated by Django 4.0.3 on 2022-04-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'permissions': (('add_picture_in_own_album', 'Добавлять фото в свой альбом'), ('change_picture_in_own_album', 'Удалять фото из своего альбома')), 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
    ]
